#server.port=80

#spring.datasource.url= jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf8&useSSL=false
#spring.datasource.username= root
#spring.datasource.password= 123456
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#mybatis.config-location=classpath:mybatis-config.xml
server:
    port: 8080
    address: 127.0.0.1
    sessionTimeout: 30
    contextPath: /
spring:
  mvc:
    static-path-pattern : /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  devtools:
        restart:
            #热部署生效
          enabled: true
            #设置重启的目录
            #additional-paths: src/main/java
            #classpath目录下的WEB-INF文件夹内容修改不重启
          exclude: WEB-INF/**
  thymeleaf:
    mode : LEGACYHTML5
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class: com.mysql.jdbc.Driver


  # Server settings (ServerProperties)


